### PR TITLE
Adding retrying when trying to fetch changes

### PR DESCRIPTION
**Pull request by AgustinCB**

### CODE REVIEW

**Comment by kbourgoin** [comment]
Hi @AgustinCB,

Thanks for the contribution! Would you mind adding some tests for this case so that we know precisely what's being fixed and can verify that it's all correct?

Thanks!

**Comment by AgustinCB** [comment]
Hi @kbourgoin,

Yes, no problem. Is there any way to fake a broker going down into the test suite? I took a look into the current tests and don't see the case. 

Thank you.

**Comment by emmettbutler** [comment]
Maybe to simulate a broker connection being lost, you can manipulate [`Broker._connection`](https://github.com/Parsely/pykafka/blob/master/pykafka/broker.py#L196) by calling its [`disconnect()`](https://github.com/Parsely/pykafka/blob/master/pykafka/connection.py#L83) method.

**Comment by emmettbutler** [comment]
@AgustinCB If you'd like to open a pull request against the main pykafka repo with these changes + tests, I'd be happy to review them.

**Comment by AgustinCB** [comment]
I know, but the tests still needs some finetuning! Thank you.

**Pull request merged**
